/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kr.appkr.thrift.errors;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 에러 코드
 */
public enum ErrorCode implements org.apache.thrift.TEnum {
  /**
   * 일반적인 클라이언트 에러
   */
  BAD_REQUEST(400),
  /**
   * 요청한 리소스가 서버에 없음
   */
  NOT_FOUND(404),
  /**
   * 클라이언트가 제시한 파라미터 값/형식이 기대 요건을 충족하지 않음
   */
  UNPROCESSIBLE_ENTITY(422),
  /**
   * General server error
   */
  INTERNAL_SERVER_ERROR(500);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 400:
        return BAD_REQUEST;
      case 404:
        return NOT_FOUND;
      case 422:
        return UNPROCESSIBLE_ENTITY;
      case 500:
        return INTERNAL_SERVER_ERROR;
      default:
        return null;
    }
  }
}
