<?php
namespace Appkr\Thrift\Post;
/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * Post 서비스
 */
interface PostServiceIf {
  /**
   * 포스트 목록을 응답합니다.
   * 
   * @param \Appkr\Thrift\Post\QueryFilter $qf
   * @param int $offset
   * @param int $limit
   * @return \Appkr\Thrift\Post\Post[] PostCollection 엔티티
   * 
   * @throws \Appkr\Thrift\Errors\UserException
   * @throws \Appkr\Thrift\Errors\SystemException
   */
  public function all(\Appkr\Thrift\Post\QueryFilter $qf, $offset, $limit);
  /**
   * 특정 포스트의 상세 정보를 응답합니다.
   * 
   * @param int $id
   * @return \Appkr\Thrift\Post\Post Post 엔티티
   * 
   * @throws \Appkr\Thrift\Errors\UserException
   * @throws \Appkr\Thrift\Errors\SystemException
   */
  public function find($id);
  /**
   * 새 포스트를 만듭니다.
   * 
   * @param string $title
   * @param string $content
   * @return \Appkr\Thrift\Post\Post Post 엔티티
   * 
   * @throws \Appkr\Thrift\Errors\UserException
   * @throws \Appkr\Thrift\Errors\SystemException
   */
  public function store($title, $content);
}


