<?php
namespace Appkr\Thrift\Post;

/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * 쿼리 필터 엔티티
 */
class QueryFilter {
  static $_TSPEC;

  /**
   * 검색할 키워드
   * 
   * @var string
   */
  public $keyword = "";
  /**
   * 정렬 기준이 되는 필드
   * 
   * @var string
   */
  public $sortBy = "created_at";
  /**
   * 정렬 방향
   * 
   * @var string
   */
  public $sortDirection = "desc";

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'keyword',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'sortBy',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'sortDirection',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['keyword'])) {
        $this->keyword = $vals['keyword'];
      }
      if (isset($vals['sortBy'])) {
        $this->sortBy = $vals['sortBy'];
      }
      if (isset($vals['sortDirection'])) {
        $this->sortDirection = $vals['sortDirection'];
      }
    }
  }

  public function getName() {
    return 'QueryFilter';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->keyword);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->sortBy);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->sortDirection);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('QueryFilter');
    if ($this->keyword !== null) {
      $xfer += $output->writeFieldBegin('keyword', TType::STRING, 1);
      $xfer += $output->writeString($this->keyword);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->sortBy !== null) {
      $xfer += $output->writeFieldBegin('sortBy', TType::STRING, 2);
      $xfer += $output->writeString($this->sortBy);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->sortDirection !== null) {
      $xfer += $output->writeFieldBegin('sortDirection', TType::STRING, 3);
      $xfer += $output->writeString($this->sortDirection);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

